[build]
builder = "nixpacks"
buildCommand = """
    conda create -n candystore python=3.10 -y && \
    conda activate candystore && \
    pip install -e . && \
    jupyter nbextension enable --py --sys-prefix ipyleaflet
"""

[deploy]
startCommand = "echo Deployment started"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
